version: '3.8'
services:
  datagram:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        UBUNTU_VERSION: ${UBUNTU_VERSION:-22.04}
    platform: linux/amd64
    environment:
      - DATAGRAM_KEY=${DATAGRAM_KEY}
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    container_name: datagram
    restart: unless-stopped